### ISSUE TITLE
Review gateway_implementation flag

### ISSUE THREAD

**Issue by deepthi** [planetscale/vitess-operator#110]
https://github.com/planetscale/vitess-operator/blob/master/pkg/operator/vtgate/deployment.go#L46

sets `gateway_implementation=discoverygateway`. 

We should consider changing the default to `tabletgateway` which will be the new default vitess value in the upcoming 7.0 release.

**Comment by enisoc** [comment]
@deepthi Is there any kind of migration process needed, or should it be fine to just flip the flag on vtgates one at a time in any order?

**Comment by deepthi** [comment]
It should be fine to flip one at a time. 
There are no known compatibility issues.

**Comment by enisoc** [comment]
This was fixed by #138.
