### ISSUE TITLE
Hot loop when using AlwaysPullImages admission controller

### ISSUE THREAD

**Issue by enisoc** [planetscale/vitess-operator#111]
We've received a report of a hot loop that occurs when these conditions are met:

- The vttablet image is set to use the `:latest` tag.
- The `updateStrategy` is set to `type: Immediate`.
- The `imagePullPolicies` field is left unset.

I will try to reproduce this. In the meantime, a potential workaround is to explicitly fill in [`imagePullPolicies`](https://vitess-operator.planetscale.dev/api/#planetscale.com/v2.VitessImagePullPolicies) in the VitessCluster spec, making sure to set a non-empty value for any Vitess component for which you are using a `:latest` image (vtctld, vtgate, vttablet, vtbackup, mysqld, mysqldExporter).

**Comment by aquarapid** [comment]
This has also been reported with specific (non-latest) image tags.

**Comment by enisoc** [comment]
I haven't had a chance to try to reproduce this yet, but this might be related to the use of the [AlwaysPullImages](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages) admission controller.

**Comment by karouvirae** [comment]
This issue has actually occurred to me on an OVH-cluster. Explicitly setting the imagePullPolicies to "IfNotPresent" had no effect - using "Always", however, solved the issue. So +1 for the possibility of the AlwaysPullImages admission controller being at fault here.

(Thanks @enisoc - this actually got me to try "Always" after using IfNotPresent failed)

**Comment by karouvirae** [comment]
This issue has actually occurred to me on an OVH-cluster. Explicitly setting the imagePullPolicies to "IfNotPresent" had no effect - using "Always", however, solved the issue. So +1 for the possibility of the AlwaysPullImages admission controller being at fault here.

(Thanks @enisoc - this actually got me to try "Always" after using "IfNotPresent" failed)

EDIT: In my case, the issue occurred with _:latest_ as well as _v6.0.20-20200429_ - It probably doesn't really have anything to do with the chosen tag.

Lastly, just in case this is helpful in any way at all, here is the error I've observed everytime operator chose to terminate a pod:

> time="2020-08-31T02:47:38Z" level=info msg="Reconciling VitessCluster" VitessCluster=example controller=VitessCluster namespace=default
> {"level":"error","ts":1598842058.9388006,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"vitessshard-controller","request":"default/example-example-x-x-32601c03","error":"Operation cannot be fulfilled on pods \"example-vttablet-test-1746968200-c4d296df\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tC:/Users/Danny/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tC:/Users/Danny/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tC:/Users/Danny/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tC:/Users/Danny/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tC:/Users/Danny/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tC:/Users/Danny/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tC:/Users/Danny/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
