### ISSUE TITLE
Permit usage of "_" character in keyspace name

### ISSUE THREAD

**Issue by maZahaca** [planetscale/vitess-operator#164]
Following this issue: https://github.com/vitessio/vitess/issues/6755

We have names of the tables containing "_", so in original database we have `database_name` and in vitess operated database we have keyspace `databasename` which reduces the simplicity of migration process.

With that issue we have to do many changes to the application itself, so originally we cannot run vitess - original db in some canary setup.

**Comment by enisoc** [comment]
This should be supported as of #160, which is present in Vitess Operator v2.1.0 and up.

**Comment by aberfeldy** [comment]
With planetscale/vitess-operator:v2.1.0 and planetscale/vitess-operator:v2.2.0 running in Kubernetes I still get this error  on the operator creating a keyspace like `xxxxdw_bisources`
 
```json
{
	"level": "error",
	"ts": 1609844711.1003554,
	"logger": "controller-runtime.controller",
	"msg": "Reconciler error",
	"controller": "vitesscluster-controller",
	"request": "xxxx-stage-vitess/xxxx-stage",
	"error": "VitessKeyspace.planetscale.com \"xxxx-stage-xxxxdw-bisources-17d9900b\" is invalid: spec.name: Invalid value: \"\": spec.name in body should match '^[a-z0-9]([a-z0-9]*[a-z0-9])?$'",
	"stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"
}
```

**Comment by enisoc** [comment]
Did you re-apply all the CRDs as well when you upgraded vitess-operator? The validation is defined in those files: `deploy/crds/*.yaml`.

**Comment by aberfeldy** [comment]
Yes, I first got the error while applying the my vitesscluster, but after updating the CRD's, kubectl was not throwing an error, but the operator still reports it.

**Comment by enisoc** [comment]
Is it possible that you applied the new top-level VitessCluster CRD, but not the new versions of lower-level CRDs used by the operator like VitessKeyspace?

**Comment by aberfeldy** [comment]
So I applied the "Operator installation file" from  https://docs.planetscale.com/vitess-operator/gcp-quickstart which still seems to provide the `^[a-z0-9]([a-z0-9]*[a-z0-9])?$` pattern.

**Comment by enisoc** [comment]
Sorry, the files used in the quickstart are a snapshot that's out of date. Currently, the only way to get the matching CRDs for vitess-operator v2.2.0 is directly from GitHub:

https://github.com/planetscale/vitess-operator/tree/v2.2.0/deploy/crds

**Comment by aberfeldy** [comment]
ahh thank you, works fine now.

**Comment by aquarapid** [comment]
Closing, as #160 fixed this
