### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [planetscale/vitess-operator#182]
Hi thanks for the lib! I wonder whether this operator is ready for production?

**Comment by prime-minister-of-fun** [comment]
No it is not.  Among other things, there is only one user defined and that user has root access.

**Comment by fzyzcjy** [comment]
Ah :/ Thanks!

**Comment by frouioui** [comment]
Duplicate of https://github.com/planetscale/vitess-operator/issues/394, closing this issue for now.
