### ISSUE TITLE
Is there a schedule to support newer Kubernetes versions > 1.17?

### ISSUE THREAD

**Issue by lsylvain** [planetscale/vitess-operator#191]
Given that the Helm chart has been deprecated I decided the operator was a better alternative.  We are using Kubernetes 1.18.6 and the operator does not work in our cluster.  I happened upon a compatibility link to this project in slack and discovered the latest version of Kubernetes vitess is compatible with is 1.17.  Are there specific plans to make the operator compatible with newer Kubernetes versions.

BTW, it would had been useful if  Kubernetes version compatibility information was in the vitessio/vitess project, directly or via a link to this project.

**Comment by aquarapid** [comment]
We use 1.18.9 without issues, so I suspect your issues might not be related to the k8s version?  Can you share the specific problem(s) you are seeing?

**Comment by LittleBenx86** [comment]
Hi, I used the vitess operator to deploy vitess cluster in our k8s development environment (rancher v2.5.5 and k8s v1.19.6). When I followed the [https://vitess.io/docs/get-started/operator/](https://vitess.io/docs/get-started/operator/), that example etcd and vttablet always stopped by the readiness health check (mainly some tcp connection refused).

service:
![image](https://user-images.githubusercontent.com/19279530/116210947-f0544980-a775-11eb-9505-4927ed966ffc.png)

example etcd:
![image](https://user-images.githubusercontent.com/19279530/116210353-5db3aa80-a775-11eb-8675-cc18d792248d.png)

![image](https://user-images.githubusercontent.com/19279530/116210808-cac74000-a775-11eb-986f-ed0b526d5d53.png)

vttablet:
![image](https://user-images.githubusercontent.com/19279530/116210480-7de36980-a775-11eb-90bb-eedee56abefb.png)

![image](https://user-images.githubusercontent.com/19279530/116210573-93589380-a775-11eb-806d-f4cfa8ff7e1a.png)

![image](https://user-images.githubusercontent.com/19279530/116210712-b4b97f80-a775-11eb-884c-ee7203db97fd.png)

![image](https://user-images.githubusercontent.com/19279530/116210884-da468900-a775-11eb-89d7-a7480f06221f.png)

**Comment by aquarapid** [comment]
I would focus on the etcd issue;  from the logs it seems to be having issues talking to it's peers (the IO timeouts for port 2380).  Does rancher add any implicit network policy that would prevent pods from talking to each other?

**Comment by deepthi** [comment]
We are now at 1.22+, hence no longer relevant. Please re-open if you have problems with newer k8s versions.
