### ISSUE TITLE
How does MysqldImage Work?

### ISSUE THREAD

**Issue by prime-minister-of-fun** [planetscale/vitess-operator#198]
Documentation says:
```
MysqldImage
(Appears on: VitessImages, VitessKeyspaceImages)

MysqldImage specifies the container image to use for mysqld, as well as declaring which MySQL flavor setting in Vitess the image is compatible with.
```

You've got a commented-out example for what seems like VitessImages, which is great.

But, no idea how to get the tags associated with an image.   And just uncommenting 
  images:
    mysqld:
      mysql80Compatible:

creates containers with mysql57 running.

**Comment by aquarapid** [comment]
Are you referring to a tag that has the MySQL 8.0 included (e.g. the `mysql80` or `percona80` tags if using vitess/lite?).

For example:

```
    images:
      mysqld:
        mysql80Compatible:  vitess/lite:mysql80
```

(assuming you can pull transparently from docker hub;  otherwise you will need to adjust the image url)

**Comment by prime-minister-of-fun** [comment]
Perfect! Thank you.
