### ISSUE TITLE
missing backup args for vtctld

### ISSUE THREAD

**Issue by L3o-pold** [planetscale/vitess-operator#245]
Following the discussion on Slack https://vitess.slack.com/archives/C0PQY0PTK/p1635093608043400.

vtctld is clearly missing the backup parameters like --s3_backup_aws_endpoint=s3.endpoint.com.

**Comment by deepthi** [comment]
Full set of flags needed for s3:
```
      --backup_storage_implementation=s3
      --s3_backup_aws_endpoint=s3.endpoint.com
      --s3_backup_aws_region=eu-central-003
      --s3_backup_storage_bucket=fake-bucket-name
      --s3_backup_storage_root=vt
```
There are similar flags for `gcs`

**Comment by tokikanno** [comment]
You'll also need to update s3 credential files manually if you've configured in the backup > locations > authSecret section.

* extraVolumes
* extraVolumeMounts
* extraEnv (mainly for `AWS_SHARED_CREDENTIALS_FILE`)

have to be manually patched via CRD yaml for letting vtctld backup related commands working.

**Comment by voarsh2** [comment]
Any progress or thoughts on this?

**Comment by frouioui** [comment]
Hey @L3o-pold are you still experiencing this issue?

**Comment by L3o-pold** [comment]
@frouioui the `s3_backup_aws_endpoint` flag seems available on `vtctld` now
