### ISSUE TITLE
Version compatibility chart in readme is out of date

### ISSUE THREAD

**Issue by deepthi** [planetscale/vitess-operator#267]
Right now we have operator `v2.6.*` with vitess `v12.0.*` and `v2.7.*` also with vitess `v12.0.*`.
We should change it to

`v2.6.*` - Vitess `v12.0.*` and `v13.0.*`
`v2.7.*` - Vitess `v14.0.*`

It is worth reviewing the whole document to see if anything else needs to be changed.

**Comment by Verolop** [comment]
I think @frouioui updated this here: https://github.com/planetscale/vitess-operator/commit/1e480c73a9788f907df52d7ab2ca62c7d2c0b1fc
I added Vitess `v.12.0.*` for `v2.6.*` https://github.com/planetscale/vitess-operator/pull/269
