### ISSUE TITLE
Bump the vitess image version in upgrade-downgrade tests during v14 GA

### ISSUE THREAD

**Issue by frouioui** [planetscale/vitess-operator#271]
We should bump the version of the vitess images used in the upgrade-downgrade tests once we release v14 GA. This task and the bump required for RC's (https://github.com/planetscale/vitess-operator/pull/270) should be documented in the release process.

**Comment by GuptaManan100** [comment]
https://github.com/planetscale/vitess-operator/pull/274 does this change
