### ISSUE TITLE
Keep Kubernetes supported version list up-to date

### ISSUE THREAD

**Issue by GuptaManan100** [planetscale/vitess-operator#292]
## Description

Make sure to update the kubernetes version list for the VTop and make sure it works with the latest versions.

**Comment by hoony9x** [comment]
Is there any detailed plan for this issue?

I want to use this operator on Kubernetes 1.25 (Currently latest version) but I can't because of below error message.

```json
{
    "level":"error",
    "ts":1663237492.7023168,
    "logger":"controller-runtime.source",
    "msg":"if kind is a CRD, it should be installed before calling Start",
    "kind":"PodDisruptionBudget.policy",
    "error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""
}
```
- APIVersion of `PodDisruptionBudget` might be `policy/v1`, not `policy/v1beta1`.

**Comment by jseparovic** [comment]
Any plans to go to 1.23? 1.22 is EOL later this month

**Comment by Auha** [comment]
Just to add to this is there a timeline for Kubernetes version 1.25?

**Comment by Murali-P** [comment]
Facing the same issue, What is the resolution ?

**Comment by frouioui** [comment]
Hey all, we have an opened Pull Request to support k8s `1.25`: https://github.com/planetscale/vitess-operator/pull/309, we are still working on it. We hope to support `1.25` for the next version of the vitess-operator: `2.10.0`.

**Comment by frouioui** [comment]
Since the release of v2.14 we have updated the latest version of K8S `v1.31.0` and will keep upgrading for every release of vtop.
