### ISSUE TITLE
Latest Docker images not compatible with operator

### ISSUE THREAD

**Issue by mikeyk** [planetscale/vitess-operator#326]
We have our images specified as:
`vitess/lite:mysql80`

As of this morning, though, bringing up new nodes fails with:
`unknown flag: --db-config-app-uname`
Since [this commit landed](https://github.com/vitessio/vitess/commit/c82dd87fc3e310d58db610f9592f70ba541ee635).

For our deployment we can pin to an older Docker image SHA -- should the docs be updated as well to pin to a version before these flags were removed, until the Operator is updated to remove the flags from `flags.go`?

**Comment by GuptaManan100** [comment]
@mikeyk Yes, we found the failures too from the weekly cron jobs, and the PR to fix it is at https://github.com/planetscale/vitess-operator/pull/324.
