### ISSUE TITLE
Vitess Operator API Reference is stale

### ISSUE THREAD

**Issue by yoheimuta** [planetscale/vitess-operator#354]
README.md has a link to the documentation about CRD APIs implemented by the operator.

https://github.com/planetscale/vitess-operator/blob/847bdc331c6e4976cf610d91ace78d1bf14fe9ba/README.md?plain=1#L8

But the last time when this API document was updated was [Aug 31, 2021](https://github.com/planetscale/vitess-operator/commit/f9993922ff84e703b4aa39cd11e83ea09ed5f43d). 
So, it lacks a lot of recent information.

As CONTRIBUTING.md mentions the user-facing docs for the public API, wouldn't it be useful for OSS users to hook up with https://vitess-operator.planetscale.dev/api/ instead of the out-of-date markdown file?

https://github.com/planetscale/vitess-operator/blob/847bdc331c6e4976cf610d91ace78d1bf14fe9ba/CONTRIBUTING.md?plain=1#L26-L31

**Comment by frouioui** [comment]
This is fixed by https://github.com/planetscale/vitess-operator/pull/612.
