### ISSUE TITLE
support kubernetes v1.25 for recommended stable vitess versions

### ISSUE THREAD

**Issue by jcarrig** [planetscale/vitess-operator#409]
The Kubernetes project maintains release branches for the most recent three minor releases, which are currently `v1.26`, `v1.25`, `v1.24`, and the end of life for `v1.24` is 2023-07-28 ([as documented here](https://kubernetes.io/releases/#release-v1-24)).

The Vitess maintainers support the last three major releases of Vitess, which are currently `v14`, `v15`, `v16`. ([as documented here](https://vitess.io/docs/releases/#release-history)).  

The recommended kubernetes versions for the Vitess Operator versions that correspond to the three major stable Vitess releases are shown below ([as documented here](https://github.com/planetscale/vitess-operator/blob/ddec3bdcf4b5cffaa5146425039d8a75f52ac32a/README.md)):

Vitess Operator Version | Recommended Vitess Versions | Recommended Kubernetes Versions
--- |-----------------------------| ---
`v2.7.*` | `v14.0.*`                   | `v1.20.*`, `v1.21.*`, or `v1.22.*`
`v2.8.*` | `v15.0.*`                   | `v1.22.*`, `v1.23.*`, or `v1.24.*`
`v2.9.*` | `v16.0.*`                   | `v1.22.*`, `v1.23.*`, or `v1.24.*`

A few days ago [this PR](https://github.com/planetscale/vitess-operator/pull/397) was merged adding support for kubernetes `v1.25`.  Given the end of life of kubernetes `v1.24` is approaching, I propose to patch each of the above Vitess Operator versions to support kubernetes `v1.25`.

**Comment by frouioui** [comment]
Hello @jcarrig 👋🏻  This is a good idea, we should definitely do it. Do you already have a PR to fix this?

**Comment by jcarrig** [comment]
> Hello @jcarrig 👋🏻 This is a good idea, we should definitely do it. Do you already have a PR to fix this?

@frouioui, i will work to put up some PRs 👍

**Comment by frouioui** [comment]
Tracking PRs:
- https://github.com/planetscale/vitess-operator/issues/409

**Comment by jcarrig** [comment]
more PRs: 
- https://github.com/planetscale/vitess-operator/pull/412
- https://github.com/planetscale/vitess-operator/pull/413

**Comment by frouioui** [comment]
@jcarrig looking great to me! thank you for pushing this effort, truly appreciate it 🙏🏻

**Comment by jcarrig** [comment]
releases that support kubernetes v1.25:
- https://github.com/planetscale/vitess-operator/releases/tag/v2.7.5
- https://github.com/planetscale/vitess-operator/releases/tag/v2.8.4
- and the next `v2.9.x` release (coming soon)

thanks @frouioui for your help 👍
