### ISSUE TITLE
Unable to install vitess on kubernetes behind proxy

### ISSUE THREAD

**Issue by Murali-P** [planetscale/vitess-operator#442]
The below steps are followed.

[(https://vitess.io/docs/17.0/get-started/operator/)]

example-commerce-x-x-zone1-vtorc-c13ef6ff-546c99f5f6-lprhn   1/1     Running     0                42m
example-etcd-faf13de3-1                                      1/1     Running     0                43m
example-etcd-faf13de3-2                                      1/1     Running     1 (42m ago)      43m
example-etcd-faf13de3-3                                      1/1     Running     0                43m
example-vttablet-zone1-0790125915-4e37d9d5                   2/3     Running     2 (41m ago)      42m
example-vttablet-zone1-2469782763-bfadd780                   2/3     Running     2 (41m ago)      42m
example-vttablet-zone1-2548885007-46a852d0                   2/3     Running     2 (41m ago)      42m

vttablet is not healthy.

W0707 10:03:44.586893       1 rpc_server.go:72] TabletManager.FullStatus()(on zone1-2469782763 from ) error: Access denied for user 'vt_dba'@'localhost' (using password: NO) (errno 1045) (sqlstate 28000)
W0707 10:03:44.692870       1 rpc_server.go:72] TabletManager.ReplicationStatus()(on zone1-2469782763 from ) error: Access denied for user 'vt_dba'@'localhost' (using password: NO) (errno 1045) (sqlstate 2800

**Comment by mattlord** [comment]
Hi @Murali-P,

It looks like your etcd (topo server) cluster is not healthy, thus tablets would not be able to initialize.

This is not the proper avenue for support. I'm going to close this issue. Please ask for help in [the Vitess Slack](https://vitess.io/slack) as it will require significant back and forth asking for logs, command output, execution context, version details, etc.

Best Regards
