### ISSUE TITLE
Supported Kubernetes Versions going EOL

### ISSUE THREAD

**Issue by ThisGuyCodes** [planetscale/vitess-operator#509]
The readme states:
> Our goal for Kubernetes is for the latest Vitess Operator release to be compatible with the latest Kubernetes version that's Generally Available on all of GKE, EKS, and AKS.

Currently the readme advertises support for Kubernetes 1.25.

The current latest Kubernetes version supported by [all](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions) [three](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) [platforms](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule-for-release-channels) is 1.28.

In fact, AKS will be marking 1.25 as EOL in 39 days (Jan 14th 2024), GKE will do the same in ~3 months (Feb 29th 2024), and EKS in ~6 months (May 2024). (AKS has something called "platform support" that lasts a bit longer, but they use the words "End of life" for the column I pulled the date from).

AKS gives a lovely chart showing the impeding deprecation:
![gantt chart showing AKS support lifecycle](https://learn.microsoft.com/en-us/azure/aks/media/supported-kubernetes-versions/kubernetes-versions-gantt.png)

Given Kubernetes releases happen ["approximately three times per year"](https://kubernetes.io/releases/release/#the-release-cycle:~:text=Kubernetes%20releases%20currently%20happen%20approximately%20three%20times%20per%20year.), supporting 1.25 at the latest puts support about a full year behind its stated objective.

I mean this with no ill will; this is an open source project provided for free. But I would like an honest answer; does planetscale intend on supporting / keeping this operator up to date?

**Comment by deepthi** [comment]
We plan to update the supported versions in the next release. What was missed out on was creating a public issue for that task.
