### ISSUE TITLE
Publishing ARM images

### ISSUE THREAD

**Issue by manvalls** [planetscale/vitess-operator#545]
Hi all, can you publish aarch64 images please 🙏

**Comment by manvalls** [comment]
@frouioui the only motivation I have, is that arm64 servers are considerably cheaper

**Comment by eslam-gomaa** [comment]
@frouioui running workload on ARM based instances may give 15-30% compute cost saving. while providing better performance

**Comment by silviucpp** [comment]
Both etcd and percona now has support for arm.
