### ISSUE TITLE
missing s3_backup_force_path_style 

### ISSUE THREAD

**Issue by aep** [planetscale/vitess-operator#548]
according to this change

https://github.com/vitessio/vitess/pull/4200/files

i believe s3_backup_force_path_style is needed to get backup to minio working.
hwoever, the CRD doesnt have that option in S3BackupLocation

**Comment by aep** [comment]
it isnt actually missing.    `forcePathStyle` is just missing from the docs  here https://github.com/planetscale/vitess-operator/blob/main/docs/api.md

i would just send a PR, but the docs look autogenerated and i'm not sure from what

**Comment by mattlord** [comment]
Hi @aep ! 

> it isnt actually missing.  forcePathStyle is just missing from the docs here https://github.com/planetscale/vitess-operator/blob/main/docs/api.md

Ah, I was going to say that I knew some people were using minio successfully.

> i would just send a PR, but the docs look autogenerated and i'm not sure from what

That would be awesome! ❤️ The docs are built from the `generate` makefile target:
```
generate:
        go run sigs.k8s.io/controller-tools/cmd/controller-gen object crd:maxDescLen=0 paths="./pkg/apis/planetscale/v2" output:crd:artifacts:config=./deploy/crds
        go run github.com/ahmetb/gen-crd-api-reference-docs -api-dir planetscale.dev/vitess-operator/pkg/apis/planetscale/v2 -config ./docs/api/config.json -template-dir ./docs/api/template -out-file ./docs/api/index.html
```

And the docs are built from the code in `pkg/apis/planetscale/v2/*/go`. 

I see it documented here:
```
docs/api/index.html:<code>forcePathStyle</code></br>
pkg/apis/planetscale/v2/vitessbackupstorage_types.go:   ForcePathStyle bool `json:"forcePathStyle,omitempty"`
```

What do you think it missing? You expected it to be somewhere else?

**Comment by frouioui** [comment]
Closing this for now, `ForcePathStyle` is an option in the CRD. The API documentation was out of date, and got re-generated a couple months ago.
