### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by DellanX** [planetscale/vitess-operator#551]
Is there any intent to wrap these manifests into a helm chart?

If there is none, would there be any interest in me creating a helm chart version that could live alongside this?

**Comment by deepthi** [comment]
The maintainer team does not plan to provide helm charts. You might get more responses in terms of interest in a community built helm chart by posting in slack (#kubernetes and #developers)

**Comment by frouioui** [comment]
I will close this issue for now, as recommended by Deepthi, you should continue this conversation on Slack.
