### ISSUE TITLE
user-defined per-keyspace images feature is unusable

### ISSUE THREAD

**Issue by bluecrabs007** [planetscale/vitess-operator#608]
The [issue](https://github.com/planetscale/vitess-operator/issues/446) and the [PR](https://github.com/planetscale/vitess-operator/pull/524) brings in the ability to create a new keyspace and override the mysqld container image.

This lets the user deploy a new keyspace with mysql8 in a vitesscluster deployed with mysql57 with the goal of letting the user `MoveTables` the data from the 57 keyspace to 80.

There are 2 issues with the current implementation and the version this feature was released in.

Issue 1:
This feature lets the user override the mysqld image only. This causes incompatibilities between the vttablet container and the mysqld container due to the version mismatch.
For example, the vttablet would be running the mysql57 version of xtrabackup which doesn't work with mysql80
it fails with error 
```
xtrabackupengine.go:369] xtrabackup stderr: Error: MySQL 8.0 and Percona Server 8.0 are not supported by Percona Xtrabackup 2.4.x series. Please use Percona Xtrabackup 8.0.x for backups and restores.
```
Suggestion: A bug fix to enable support for user-definable per-keyspace images for vttablet, vtorc, myqsld exporter.

Issue 2:
This feature landed in vitess-operator [v2.12.0](https://github.com/planetscale/vitess-operator/releases/tag/v2.12.0) which corresponds to vitess v19, which drops support for mysql57.
Suggestion: Backport this feature to v2.11.x so that users can migrate off mysql 57 from the last vitess version that supports mysql57

**Comment by frouioui** [comment]
Hey @bluecrabs007, thanks for opening this. This is a reasonable thing to do in vitess-operator.

I have [opened a backport](https://github.com/planetscale/vitess-operator/pull/609) to `release-2.11` for the original fix made in `v2.12`. This should solve `Issue 2`.

While it gets merged, I am working on a fix for `Issue 1`.
