### ISSUE TITLE
Catch grpc: addrConn.createTransport exceptions to prevent multiline logs

### ISSUE THREAD

**Issue by bluecrabs007** [planetscale/vitess-operator#637]
We are seeing go stacktraces from vitess-operator when it cannot connect to a thing.
either etcd endpoint or vttablet grpc
stack traces look like
```
W1115 08:55:24.028933       1 component.go:41] [core] [Channel #4 SubChannel #5] grpc: addrConn.createTransport failed to connect to {
  "Addr": "vt-etcd-ec571fc7-client.platform-dbtech-sandbox.svc:2379",
  "ServerName": "vt-etcd-ec571fc7-client.platform-dbtech-sandbox.svc",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp 100.74.28.238:2379: connect: connection refused"

```
and
```
Unlocking shard sharded/aa-ab for action electShardPrimary with error can't elect primary: didn't find any valid candidate
[core] [Channel #414416878 SubChannel #414416880] grpc: addrConn.createTransport failed to connect to {
 "Addr": ":0",
 "ServerName": "localhost:0",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp :0: connect: connection refused"
```

Steps to reproduce: Delete etcd pods or vttablet pods

**Comment by jwangace** [comment]
Ya the logs are came from single container pod vitess-operator, and seems the logs uses newline character in the end of each line, when it parsed by kibana, it spreads in multiple lines for 1 log.
![Image](https://github.com/user-attachments/assets/b24e004e-0aa0-4fae-974a-2b62e496acce)

**Comment by frouioui** [comment]
Hi @jwangace, spent some time looking into this log is produced directly by gRPC and is not in our control. It would be interesting if you share how you handled this on the app-side for future issues on this topic.

**Comment by bluecrabs007** [comment]
> Hi [@jwangace](https://github.com/jwangace), spent some time looking into this log is produced directly by gRPC and is not in our control. It would be interesting if you share how you handled this on the app-side for future issues on this topic.

We are currently not handling this anywhere and the logging stack ingests these stack traces as is, each line as a separate document.

There are 2 issues here,
1) These stack traces may not be throlled anywhere, so they occur in huge volume, when underlying components are being upgraded (vttablet rollout, for example)
2) The impact on the logging stack is amplified as each stack trace is injested as multiple documents (one per line).

Fixing either of them would help alleviate the impact.

I understand that these are being emited directly by gRPC, is there a way for the vitess-operator to catch these exceptions and log a single line instead?

**Comment by frouioui** [comment]
Quick question, what logging stack are you using? You have mentioned Kibana, but who is first processing the logs?

I am unable to reproduce the error locally but it is likely due to containerd automatically merging multi-lines logs into single-line.

**Comment by bluecrabs007** [comment]
> Quick question, what logging stack are you using? You have mentioned Kibana, but who is first processing the logs?
> 
> I am unable to reproduce the error locally but it is likely due to containerd automatically merging multi-lines logs into single-line.

we use fluentbit and also `kubectl logs` does show the tracebacks as multiple lines.

**Comment by bluecrabs007** [comment]
@frouioui 

Looks like I am unable to repro this issue using v21 but able to using v16.
So somewhere along the way, it looks like vitess-operator received an library update that fixes this.

To repro in v16
```
$ git checkout tags/v16.0.2
$ minikube start --kubernetes-version=v1.28.5 --cpus=4 --memory=11000 --disk-size=32g
$ kubectl apply -f examples/operator/operator.yaml
$ kubectl apply -f examples/operator/101_initial_cluster.yaml
$ kubectl logs -l app=vitess-operator -f
......
W1204 20:46:24.855746       1 component.go:41] [core] [Channel #81 SubChannel #82] grpc: addrConn.createTransport failed to connect to {
  "Addr": "example-etcd-faf13de3-client.default.svc:2379",
  "ServerName": "example-etcd-faf13de3-client.default.svc",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.111.54.89:2379: connect: connection refused"
...... 
```

So i think its fine to close this issue as this is no longer an issue in the latest version, although i am curious as to what exact change fixes this.
