### ISSUE TITLE
Add setting to disable replication repair

### ISSUE THREAD

**Issue by enisoc** [planetscale/vitess-operator#85]
When running something like Orchestrator alongside Vitess, it's best to disable the replication repair feature of Vitess Operator so only one agent tries to fix the master. We would need to add a new field under [replication](https://vitess-operator.planetscale.dev/api/#planetscale.com/v2.VitessReplicationSpec) to support this, since replication repair is currently always on.

**Comment by luisfmcalado** [comment]
I was able to test without the orchestrator that it keeps the master as read-only when the repair is disabled. I'm having some issues with Vitess + orchestrator configuration so I wasn't able to test if the race condition issue is fixed.

**Comment by luisfmcalado** [comment]
I've tested with vitess + orchestrator (mysql flavor) and a new master was elected without any issues.
